#!/bin/bash
INDEX_REQUESTS_DIR=/data/index-requests
LOCKFILE=/tmp/indexer.lock
if [[ -f $LOCKFILE ]]; then
    echo "Lock exists. "
    exit 1
fi
for f in $INDEX_REQUESTS_DIR/*.request; do
    if [ ! -f "$f"  ]; then 
	continue
    fi
    echo "Processing: $f"
    index=$(basename $f)
    index="${index%.*}"
    mv -f $f $INDEX_REQUESTS_DIR/$index.processing
    nice -n 19 ionice -c2 -n7 indexer --rotate "$index" >$INDEX_REQUESTS_DIR/$index.processing 2>&1
    mv -f $INDEX_REQUESTS_DIR/$index.processing $INDEX_REQUESTS_DIR/$index.done
done
sleep 5
rm -f $LOCKFILE

for f in $INDEX_REQUESTS_DIR/*.request; do
    if [ ! -f "$f"  ]; then 
	continue
    fi
    echo "Checking for requeue: $f"
    bash $0
    exit 0
done
